---
sudo: required

services:
  - docker

env:
  global:
    - SITE=test.yml
  matrix:
    - DOCKER_IMAGE=ubuntu:12.04
    - DOCKER_IMAGE=ubuntu:14.04
    - DOCKER_IMAGE=centos:6
    - DOCKER_IMAGE=centos:7
    - DOCKER_IMAGE=debian:jessie
    - DOCKER_IMAGE=fedora:22
    - DOCKER_IMAGE=fedora:23
    - DOCKER_IMAGE=oraclelinux:6
    - DOCKER_IMAGE=oraclelinux:7

before_install:
  - "docker pull $DOCKER_IMAGE"

script:
  - "docker run -t -v $(pwd)/../:/base $DOCKER_IMAGE /bin/bash -c \"cd /base/ansible-java-role ; /bin/bash -xe tests/test.sh;\""
