---
- name: Install WebUpd8 Team Java PPA (for Oracle Java)
  apt_repository: repo='ppa:webupd8team/java' state=present
  when: _java_needs_oracle
  register: webupd8ppa
  until: webupd8ppa|success
  retries: 5
  delay: 10

- name: Remove WebUpd8 Team Java PPA (for Oracle Java)
  apt_repository: repo='ppa:webupd8team/java' state=present
  when: not _java_needs_oracle
